### Inscription
POST http://localhost:8000/index.php?action=register_user
Host: http://localhost:8000autisme_france
Content-Type: application/x-www-form-urlencoded

nom=Omeny&
prenom=Jihn&
email=pierreychnightder52255@gmail.com&
password=ychnightder&
voie=Exempl&
codepostale=93240&
ville=Stains&
pays=France&
telephone=0123256789
###

### Connexion
POST http://localhost:8000/index.php?action=connect_user
Host: http://localhost:8000
Content-Type: application/x-www-form-urlencoded

email=pierreychnightder52@gmail.com&
password=ychnightder
###

### Connexion-admin
POST http://localhost:8000/index.php?action=connect_admin
Host: http://localhost:8000
Content-Type: application/x-www-form-urlencoded

identifiant=pierreychnightder52@gmail.com&
password=ychnightder
###