### Inscription
POST http://localhost:8000/index.php?action=register_user
Host: http://localhost:8000
Content-Type: application/x-www-form-urlencoded

nom=Omen&
prenom=Jihn&
email=Omen25@riot.com&
password=25878ww&
voie=Exempl&
codepostale=75016&
ville=Paris&
pays=France&
telephone=0123256789
###

### Connexion
POST http://localhost:8000/index.php?action=connect_user
Host: http://localhost:8000
Content-Type: application/x-www-form-urlencoded

email=pierreychnightder52@gmail.com&
password=ychnightder
###

### Connexion-admin
POST http://localhost:8000/index.php?action=connect_admin
Host: http://localhost:8000
Content-Type: application/x-www-form-urlencoded

identifiant=pierreychnightder52@gmail.com&
password=ychnightder
###