INSERT INTO options (id_option, id_question, option_text) VALUES (1, 1, 'Moins de 18 ans');
INSERT INTO options (id_option, id_question, option_text) VALUES (2, 1, '18-25 ans');
INSERT INTO options (id_option, id_question, option_text) VALUES (3, 1, '26-40 ans');
INSERT INTO options (id_option, id_question, option_text) VALUES (4, 1, '41-60 ans');
INSERT INTO options (id_option, id_question, option_text) VALUES (5, 1, 'Plus de 60 ans');
INSERT INTO options (id_option, id_question, option_text) VALUES (6, 2, 'Féminin');
INSERT INTO options (id_option, id_question, option_text) VALUES (7, 2, 'Masculin');
INSERT INTO options (id_option, id_question, option_text) VALUES (8, 2, 'Autre');
INSERT INTO options (id_option, id_question, option_text) VALUES (9, 2, 'Préfère ne pas répondre');
INSERT INTO options (id_option, id_question, option_text) VALUES (10, 3, 'Personne autiste');
INSERT INTO options (id_option, id_question, option_text) VALUES (11, 3, 'Parent/proche aidant');
INSERT INTO options (id_option, id_question, option_text) VALUES (12, 3, 'Professionnel de santé');
INSERT INTO options (id_option, id_question, option_text) VALUES (13, 3, 'Enseignant');
INSERT INTO options (id_option, id_question, option_text) VALUES (14, 3, 'Autre');
INSERT INTO options (id_option, id_question, option_text) VALUES (15, 4, 'Moins d’un an');
INSERT INTO options (id_option, id_question, option_text) VALUES (16, 4, '1 à 3 ans');
INSERT INTO options (id_option, id_question, option_text) VALUES (17, 4, 'Plus de 3 ans');
INSERT INTO options (id_option, id_question, option_text) VALUES (18, 5, 'Île-de-France');
INSERT INTO options (id_option, id_question, option_text) VALUES (19, 5, 'Provence-Alpes-Côte d\'Azur');
INSERT INTO options (id_option, id_question, option_text) VALUES (20, 5, 'Auvergne-Rhône-Alpes');
INSERT INTO options (id_option, id_question, option_text) VALUES (21, 5, 'Nouvelle-Aquitaine');
INSERT INTO options (id_option, id_question, option_text) VALUES (22, 5, 'Hauts-de-France');
INSERT INTO options (id_option, id_question, option_text) VALUES (23, 5, 'Bretagne');
INSERT INTO options (id_option, id_question, option_text) VALUES (24, 5, 'Normandie');
INSERT INTO options (id_option, id_question, option_text) VALUES (25, 5, 'Occitanie');
INSERT INTO options (id_option, id_question, option_text) VALUES (26, 5, 'Grand Est');
INSERT INTO options (id_option, id_question, option_text) VALUES (27, 5, 'Centre-Val de Loire');
INSERT INTO options (id_option, id_question, option_text) VALUES (28, 5, 'Pays de la Loire');
INSERT INTO options (id_option, id_question, option_text) VALUES (29, 5, 'Bourgogne-Franche-Comté');
INSERT INTO options (id_option, id_question, option_text) VALUES (30, 5, 'Corse');
INSERT INTO options (id_option, id_question, option_text) VALUES (31, 6, 'Oui');
INSERT INTO options (id_option, id_question, option_text) VALUES (32, 6, 'Partiellement');
INSERT INTO options (id_option, id_question, option_text) VALUES (33, 6, 'Non');
INSERT INTO options (id_option, id_question, option_text) VALUES (34, 7, 'Oui');
INSERT INTO options (id_option, id_question, option_text) VALUES (35, 7, 'Non');
INSERT INTO options (id_option, id_question, option_text) VALUES (36, 8, 'Moins de 1h');
INSERT INTO options (id_option, id_question, option_text) VALUES (37, 8, '1h-2h');
INSERT INTO options (id_option, id_question, option_text) VALUES (38, 8, 'Plus de 2h');
INSERT INTO options (id_option, id_question, option_text) VALUES (39, 9, 'Scolarité en milieu ordinaire');
INSERT INTO options (id_option, id_question, option_text) VALUES (40, 9, 'Scolarité en dispositif spécialisé de l\'Éducation Nationale');
INSERT INTO options (id_option, id_question, option_text) VALUES (41, 9, 'Instruction en Famille');
INSERT INTO options (id_option, id_question, option_text) VALUES (42, 9, 'Scolarité dans un établissement médico-social (IME, IMPRO, IME, SESSAD, FAM, Foyer de vie)');
INSERT INTO options (id_option, id_question, option_text) VALUES (43, 9, 'Formation professionnelle');
INSERT INTO options (id_option, id_question, option_text) VALUES (44, 9, 'Études supérieures');
INSERT INTO options (id_option, id_question, option_text) VALUES (45, 9, 'Activité professionnelle en milieu ordinaire');
INSERT INTO options (id_option, id_question, option_text) VALUES (46, 9, 'Activité professionnelle en milieu protégé (ESAT, Entreprise adaptée)');
INSERT INTO options (id_option, id_question, option_text) VALUES (47, 9, 'Sans aucune activité scolaire ou professionnelle');
INSERT INTO options (id_option, id_question, option_text) VALUES (48, 9, 'Autre');
INSERT INTO options (id_option, id_question, option_text) VALUES (49, 10, 'Oui');
INSERT INTO options (id_option, id_question, option_text) VALUES (50, 10, 'Non');
INSERT INTO options (id_option, id_question, option_text) VALUES (51, 11, 'Tout va bien');
INSERT INTO options (id_option, id_question, option_text) VALUES (52, 11, 'Restriction de la vie sociale');
INSERT INTO options (id_option, id_question, option_text) VALUES (53, 11, 'Souffrance psychologique');
INSERT INTO options (id_option, id_question, option_text) VALUES (54, 11, 'Fatigue, épuisement');
INSERT INTO options (id_option, id_question, option_text) VALUES (55, 11, 'Conflits familiaux');
INSERT INTO options (id_option, id_question, option_text) VALUES (56, 11, 'Coûts financiers importants');
INSERT INTO options (id_option, id_question, option_text) VALUES (57, 11, 'Réduction d\'activité professionnelle');
INSERT INTO options (id_option, id_question, option_text) VALUES (58, 11, 'Eloignement de la personne');
INSERT INTO options (id_option, id_question, option_text) VALUES (59, 12, 'Santé');
INSERT INTO options (id_option, id_question, option_text) VALUES (60, 12, 'Travail');
INSERT INTO options (id_option, id_question, option_text) VALUES (61, 12, 'Finances');
INSERT INTO options (id_option, id_question, option_text) VALUES (62, 12, 'Accès aux soins');
INSERT INTO options (id_option, id_question, option_text) VALUES (63, 12, 'Autre');
INSERT INTO options (id_option, id_question, option_text) VALUES (64, 13, '1 (aucun impact)');
INSERT INTO options (id_option, id_question, option_text) VALUES (65, 13, '2');
INSERT INTO options (id_option, id_question, option_text) VALUES (66, 13, '3');
INSERT INTO options (id_option, id_question, option_text) VALUES (67, 13, '4');
INSERT INTO options (id_option, id_question, option_text) VALUES (68, 13, '5 (impact majeur)');
INSERT INTO options (id_option, id_question, option_text) VALUES (69, 14, 'Aide financière');
INSERT INTO options (id_option, id_question, option_text) VALUES (70, 14, 'Aide administratif');
INSERT INTO options (id_option, id_question, option_text) VALUES (71, 14, 'Soutien psychologique');
INSERT INTO options (id_option, id_question, option_text) VALUES (72, 14, 'Informations juridiques');
INSERT INTO options (id_option, id_question, option_text) VALUES (73, 14, 'Conseils éducatifs');
INSERT INTO options (id_option, id_question, option_text) VALUES (74, 14, 'Autre');
INSERT INTO options (id_option, id_question, option_text) VALUES (75, 15, 'Oui');
INSERT INTO options (id_option, id_question, option_text) VALUES (76, 15, 'Non');
INSERT INTO options (id_option, id_question, option_text) VALUES (77, 16, 'Oui');
INSERT INTO options (id_option, id_question, option_text) VALUES (78, 16, 'Non');
INSERT INTO options (id_option, id_question, option_text) VALUES (79, 17, 'Champ libre');
INSERT INTO options (id_option, id_question, option_text) VALUES (80, 18, 'Champ libre');
INSERT INTO options (id_option, id_question, option_text) VALUES (81, 19, 'Champ libre');
INSERT INTO options (id_option, id_question, option_text) VALUES (82, 20, 'Oui');
INSERT INTO options (id_option, id_question, option_text) VALUES (83, 20, 'Non');
INSERT INTO options (id_option, id_question, option_text) VALUES (84, 21, 'Oui');
INSERT INTO options (id_option, id_question, option_text) VALUES (85, 21, 'Non');
